CREATE TABLE IF NOT EXISTS ff_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ff_users (email TEXT PRIMARY KEY, role TEXT NOT NULL DEFAULT 'editor', channels_json TEXT NOT NULL DEFAULT '[]', permissions_json TEXT NOT NULL DEFAULT '{}', disabled INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ff_settings (key TEXT PRIMARY KEY, cipher TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ff_channels (id TEXT PRIMARY KEY, title TEXT NOT NULL, uploads TEXT NOT NULL, credential TEXT NOT NULL, scopes_json TEXT NOT NULL, auth_state TEXT NOT NULL DEFAULT 'connected', connected_at TEXT NOT NULL, synced_at TEXT, reach_job TEXT, ctr_unit TEXT NOT NULL DEFAULT 'unknown', ctr_unit_source TEXT, last_error TEXT);
CREATE TABLE IF NOT EXISTS ff_videos (channel_id TEXT NOT NULL, id TEXT NOT NULL, title TEXT NOT NULL, published_at TEXT, duration REAL, lifetime_views INTEGER, thumbnail_key TEXT, thumbnail_url TEXT, thumbnail_status TEXT NOT NULL DEFAULT 'pending', metadata_json TEXT NOT NULL DEFAULT '{}', observed_at TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '', tags TEXT NOT NULL DEFAULT '', PRIMARY KEY(channel_id,id));
CREATE INDEX IF NOT EXISTS ff_videos_views ON ff_videos(channel_id,lifetime_views DESC,id);
CREATE INDEX IF NOT EXISTS ff_videos_published ON ff_videos(channel_id,published_at DESC,id);
CREATE TABLE IF NOT EXISTS ff_oauth_states (id TEXT PRIMARY KEY, email TEXT NOT NULL, subject TEXT NOT NULL, cipher TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS ff_tasks (id TEXT PRIMARY KEY, channel_id TEXT NOT NULL, kind TEXT NOT NULL, status TEXT NOT NULL, start_date TEXT, end_date TEXT, options_json TEXT NOT NULL DEFAULT '{}', created_by TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', error TEXT);
CREATE INDEX IF NOT EXISTS ff_tasks_channel ON ff_tasks(channel_id,created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS ff_tasks_active ON ff_tasks(channel_id,kind) WHERE status IN ('queued','running');
CREATE TABLE IF NOT EXISTS ff_work (id TEXT PRIMARY KEY, task_id TEXT NOT NULL, kind TEXT NOT NULL, payload_json TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0, lease_until INTEGER NOT NULL DEFAULT 0, lease_token TEXT, error TEXT, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS ff_work_task ON ff_work(task_id,status);
CREATE TABLE IF NOT EXISTS ff_reports (id TEXT PRIMARY KEY, channel_id TEXT NOT NULL, video_id TEXT NOT NULL, kind TEXT NOT NULL, name TEXT NOT NULL, start_date TEXT NOT NULL, end_date TEXT NOT NULL, source TEXT NOT NULL, status TEXT NOT NULL, data_json TEXT NOT NULL DEFAULT '{}', raw_key TEXT, error TEXT, updated_at TEXT NOT NULL, task_id TEXT);
CREATE INDEX IF NOT EXISTS ff_reports_video ON ff_reports(channel_id,video_id,start_date,end_date,kind,updated_at DESC);
CREATE TABLE IF NOT EXISTS ff_reach (channel_id TEXT NOT NULL, video_id TEXT NOT NULL, day TEXT NOT NULL, impressions INTEGER NOT NULL, ctr_raw REAL, report_id TEXT NOT NULL, PRIMARY KEY(channel_id,video_id,day));
CREATE INDEX IF NOT EXISTS ff_reach_day ON ff_reach(channel_id,day,video_id);
CREATE TABLE IF NOT EXISTS ff_reach_days (channel_id TEXT NOT NULL, day TEXT NOT NULL, report_id TEXT NOT NULL, created_at TEXT NOT NULL, raw_key TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(channel_id,day));
CREATE TABLE IF NOT EXISTS ff_audit (id INTEGER PRIMARY KEY AUTOINCREMENT, actor TEXT NOT NULL, action TEXT NOT NULL, target TEXT NOT NULL, created_at TEXT NOT NULL);
INSERT OR IGNORE INTO ff_meta(key,value) VALUES('schema_version','1');
